# Generated by Django 5.1 on 2024-09-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=10)),
                ("product_name", models.CharField(max_length=20)),
                ("productNumber", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                ("note", models.TextField()),
                (
                    "supplier",
                    models.ManyToManyField(
                        related_name="products", to="suppliers.supplier"
                    ),
                ),
            ],
        ),
    ]
