# Generated by Django 5.1 on 2024-08-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productNumber", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("note", models.TextField()),
            ],
        ),
    ]
