# Generated by Django 5.1.1 on 2024-09-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="price", field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
