# Generated by Django 5.1 on 2024-09-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="supplier",
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ManyToManyField(
                related_name="products", to="suppliers.supplier"
            ),
        ),
    ]
