# Generated by Django 5.1 on 2024-09-02 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="productNumber",
            new_name="product_id",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="product_name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="suppliers.supplier",
            ),
        ),
    ]
