# Generated by Django 5.1 on 2024-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="productNumber",
            field=models.CharField(max_length=10),
        ),
    ]
