# Generated by Django 5.1.1 on 2024-09-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="cost_price",
        ),
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
