# Generated by Django 5.1 on 2024-09-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_price"),
        ("products", "0002_rename_productnumber_product_product_id_and_more"),
    ]

    operations = []
