# Generated by Django 5.1 on 2024-09-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_merge_20240902_1655"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(),
        ),
    ]
