# Generated by Django 5.1.1 on 2024-09-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_company'),
        ('products', '0003_remove_product_delete_at_product_deleted_at'),
    ]

    operations = [
    ]
