# Generated by Django 5.1.1 on 2024-09-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_merge_20240923_2331"),
        ("products", "0005_product_updated_at_alter_product_deleted_at"),
    ]

    operations = []
