# Generated by Django 5.1.1 on 2024-09-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20240923_0142'),
        ('products', '0006_merge_20240924_0009'),
    ]

    operations = [
    ]
