# Generated by Django 5.1.1 on 2024-09-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_merge_20240924_0009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="number", field=models.CharField(max_length=20),
        ),
    ]
