# Generated by Django 5.1.1 on 2024-09-19 16:15

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0003_alter_client_state"),
        ("inventory", "0001_initial"),
        ("products", "0002_alter_product_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=15, unique=True)),
                ("price", models.PositiveIntegerField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("to_be_confirmed", "待確認"),
                            ("progress", "進行中"),
                            ("finished", "已完成"),
                        ],
                        default="progress",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="clients.client",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="products.product",
                    ),
                ),
                (
                    "stock_quantity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="inventory.inventory",
                    ),
                ),
            ],
        ),
    ]
