# Generated by Django 5.1.1 on 2024-09-20 10:18

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_orders_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="orders",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("to_be_confirmed", "待確認"),
                    ("progress", "進行中"),
                    ("finished", "已完成"),
                ],
                default="to_be_confirmed",
                max_length=50,
                protected=True,
            ),
        ),
    ]
