# Generated by Django 5.1.1 on 2024-09-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_orderproductitem_delete_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=20),
        ),
    ]
