# Generated by Django 5.1.1 on 2024-09-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_client_fk_orders_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="code",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
