# Generated by Django 5.1.1 on 2024-09-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_orders_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
