# Generated by Django 5.1.1 on 2024-09-19 16:40

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_orders_is_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("to_be_confirmed", "待確認"),
                    ("progress", "進行中"),
                    ("finished", "已完成"),
                ],
                default="to_be_confirmed",
                max_length=50,
                protected=True,
            ),
        ),
    ]
