<<<<<<<< HEAD:apps/orders/migrations/0003_order_company.py
# Generated by Django 5.1.1 on 2024-09-22 18:10
========
# Generated by Django 5.1.1 on 2024-09-23 16:09
>>>>>>>> 6bea46e045d7b1c7cbdd934606d2bcd524ffbb41:apps/orders/migrations/0004_order_company.py

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<<< HEAD:apps/orders/migrations/0003_order_company.py
        ("company", "0006_remove_company_company_id"),
        ("orders", "0002_order_orderproductitem_delete_orders"),
========
        ("company", "0009_auto_20240923_1948"),
        ("orders", "0003_alter_order_order_number"),
>>>>>>>> 6bea46e045d7b1c7cbdd934606d2bcd524ffbb41:apps/orders/migrations/0004_order_company.py
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="company.company",
            ),
        ),
    ]
