# Generated by Django 5.1.1 on 2024-09-16 18:29

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_orders_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "待處理"),
                    ("progress", "進行中"),
                    ("finished", "已完成"),
                ],
                default="progress",
                max_length=50,
                protected=True,
            ),
        ),
    ]
