# Generated by Django 5.1.1 on 2024-09-22 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_remove_company_company_id"),
        ("orders", "0003_orders_is_finished_alter_orders_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="company.company",
            ),
        ),
    ]
