# Generated by Django 5.1.1 on 2024-09-20 07:31

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_state"),
        ("orders", "0004_alter_orders_state"),
        ("products", "0002_alter_product_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=11, unique=True)),
                ("client_tel", models.CharField(max_length=15)),
                ("client_address", models.CharField(max_length=150)),
                ("client_email", models.EmailField(max_length=254)),
                ("amount", models.PositiveIntegerField()),
                ("username", models.CharField(default="admin", max_length=150)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("pending", "待處理"),
                            ("progress", "進行中"),
                            ("finished", "已完成"),
                        ],
                        default="progress",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="clients.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered_quantity", models.PositiveIntegerField()),
                ("sale_price", models.PositiveIntegerField()),
                ("subtotal", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Orders",
        ),
    ]
