# Generated by Django 5.1 on 2024-08-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="note",
            field=models.TextField(max_length=150, null=True),
        ),
    ]
