# Generated by Django 5.1 on 2024-08-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_alter_client_create_at_alter_client_delete_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
