# Generated by Django 5.1.1 on 2024-09-20 16:32

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_alter_product_state"),
        ("suppliers", "0002_alter_supplier_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=11, unique=True)),
                ("supplier_tel", models.CharField(max_length=15)),
                ("contact_person", models.CharField(max_length=20)),
                ("supplier_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True, null=True)),
                ("username", models.CharField(default="admin", max_length=150)),
                (
                    "receiving_method",
                    models.CharField(
                        choices=[("貨運", "貨運"), ("自取", "自取")], max_length=20
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("to_be_restocked", "待進貨"),
                            ("to_be_stocked", "待入庫"),
                            ("finished", "完成"),
                        ],
                        default="to_be_restocked",
                        max_length=50,
                        protected=True,
                    ),
                ),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to="suppliers.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsReceiptProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered_quantity", models.PositiveIntegerField()),
                ("received_quantity", models.PositiveIntegerField()),
                ("cost_price", models.PositiveIntegerField()),
                ("subtotal", models.PositiveIntegerField()),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="goods_receipts.goodsreceipt",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
