# Generated by Django 5.1.1 on 2024-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods_receipts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceipt",
            name="order_number",
            field=models.CharField(max_length=11),
        ),
    ]


# Generated by Django 5.1.1 on 2024-09-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods_receipts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceipt",
            name="order_number",
            field=models.CharField(max_length=11),
        ),
    ]
