# Generated by Django 5.1.1 on 2024-09-22 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_remove_company_company_id"),
        ("goods_receipts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceipt",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_receipts",
                to="company.company",
            ),
        ),
    ]
