# Generated by Django 5.1.1 on 2024-09-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
