# Generated by Django 5.1.1 on 2024-09-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods_receipts", "0002_goodsreceipt_company"),
        ("goods_receipts", "0002_alter_goodsreceipt_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceipt",
            name="order_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
