# Generated by Django 5.1.1 on 2024-09-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods_receipts", "0002_goodsreceipt_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceipt",
            name="order_number",
            field=models.CharField(max_length=11),
        ),
    ]
