# Generated by Django 5.1.1 on 2024-09-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods_receipts", "0002_alter_goodsreceipt_order_number"),
        ("goods_receipts", "0002_goodsreceipt_company"),
    ]

    operations = []
