# Generated by Django 5.1.1 on 2024-09-16 17:56

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods_receipts", "0002_goodsreceipt_deleted_at_goodsreceipt_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceipt",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("to_be_restocked", "待進貨"),
                    ("to_be_stocked", "待入庫"),
                    ("finished", "完成"),
                ],
                default="to_be_restocked",
                max_length=50,
                protected=True,
            ),
        ),
    ]
