# Generated by Django 5.1.1 on 2024-09-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods_receipts", "0003_alter_goodsreceipt_order_number"),
        ("goods_receipts", "0003_merge_20240923_2331"),
    ]

    operations = []
