# Generated by Django 5.1.1 on 2024-09-19 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods_receipts", "0003_alter_goodsreceipt_state"),
        ("products", "0002_alter_product_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goodsreceipt",
            old_name="quantity",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="goodsreceipt",
            old_name="method",
            new_name="contact_person",
        ),
        migrations.RemoveField(
            model_name="goodsreceipt",
            name="date",
        ),
        migrations.RemoveField(
            model_name="goodsreceipt",
            name="goods_name",
        ),
        migrations.RemoveField(
            model_name="goodsreceipt",
            name="receipt_number",
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="order_number",
            field=models.CharField(default=0, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="receiving_method",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="supplier_email",
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="supplier_tel",
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="username",
            field=models.CharField(default="admin", max_length=150),
        ),
        migrations.AlterField(
            model_name="goodsreceipt",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="GoodsReceiptProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered_quantity", models.PositiveIntegerField()),
                ("received_quantity", models.PositiveIntegerField()),
                ("cost_price", models.PositiveIntegerField()),
                ("subtotal", models.PositiveIntegerField()),
                (
                    "goord_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods_receipt_items",
                        to="goods_receipts.goodsreceipt",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
