# Generated by Django 5.1.1 on 2024-09-19 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods_receipts", "0004_rename_quantity_goodsreceipt_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsreceiptproductitem",
            name="goord_receipt",
        ),
        migrations.AddField(
            model_name="goodsreceiptproductitem",
            name="goods_receipt",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="goods_receipts.goodsreceipt",
            ),
            preserve_default=False,
        ),
    ]
