# Generated by Django 5.1.1 on 2024-09-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "goods_receipts",
            "0005_remove_goodsreceiptproductitem_goord_receipt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceipt",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="goodsreceipt",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
