# Generated by Django 5.1.1 on 2024-09-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods_receipts", "0006_goodsreceipt_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceipt",
            name="receiving_method",
            field=models.CharField(
                choices=[("delivery", "Delivery"), ("pickup", "Pickup")], max_length=20
            ),
        ),
    ]
