# Generated by Django 5.1.1 on 2024-09-21 08:59

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_alter_supplier_state"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="supplier",
            managers=[
                ("bjects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="delete_at",
        ),
        migrations.AddField(
            model_name="supplier",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
    ]
