# Generated by Django 5.1 on 2024-09-03 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_rename_contact_supplier_contact_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="established_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
