# Generated by Django 5.1.1 on 2024-09-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0003_supplier_company"),
        ("suppliers", "0004_alter_supplier_managers"),
    ]

    operations = []
