# Generated by Django 5.1.1 on 2024-09-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0005_supplier_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
