# Generated by Django 5.1.1 on 2024-09-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0005_merge_20240923_2331"),
        ("suppliers", "0006_supplier_updated_at_alter_supplier_deleted_at"),
    ]

    operations = []
