# Generated by Django 5.1.1 on 2024-09-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_merge_20240924_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
