# Generated by Django 5.1.1 on 2024-09-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0008_alter_supplier_email"),
        ("suppliers", "0009_supplier_user"),
    ]

    operations = []
