# Generated by Django 5.1.1 on 2024-10-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_merge_0008_alter_supplier_email_0009_supplier_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='gui_number',
            field=models.CharField(max_length=8),
        ),
    ]
