# Generated by Django 5.1.1 on 2024-09-13 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_edit_department", "Can edit department"),
                    ("can_edit_position", "Can edit position"),
                    ("can_edit_hire_date", "Can edit hire date"),
                ]
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="title",
        ),
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                choices=[
                    ("", "Select Position"),
                    ("Intern", "Intern"),
                    ("Specialist", "Specialist"),
                    ("Manager", "Manager"),
                    ("BOSS", "BOSS"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                choices=[
                    ("", "Select Department"),
                    ("Purchasing", "Purchasing"),
                    ("Inventory", "Inventory"),
                    ("HR", "Human Resources"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="hire_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
