# Generated by Django 5.1.1 on 2024-09-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
