# Generated by Django 5.1.1 on 2024-09-21 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_remove_company_company_id"),
        ("users", "0002_alter_customuser_options_remove_customuser_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="CustomUser",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="first_login",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
