# Generated by Django 5.1.1 on 2024-09-21 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_user'),
        ('users', '0002_alter_customuser_options_remove_customuser_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='CustomUser', to='company.company'),
        ),
    ]
