# Generated by Django 5.1.1 on 2024-09-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="note",
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
