# Generated by Django 5.1.1 on 2024-09-21 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_user'),
        ('users', '0004_alter_customuser_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='CustomUser', to='company.company'),
        ),
    ]
