# Generated by Django 5.1.1 on 2024-09-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_notification_sender_id_notification_sender_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="sender_id",
        ),
        migrations.AddField(
            model_name="notification",
            name="sender_state",
            field=models.CharField(default="", max_length=20),
        ),
    ]
