# Generated by Django 5.1.1 on 2024-09-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_notification_sender_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
