# Generated by Django 5.1.1 on 2024-09-21 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_user'),
        ('users', '0005_alter_customuser_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='CustomUser', to='company.company'),
        ),
    ]
