# Generated by Django 5.1.1 on 2024-09-21 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_user"),
        ("users", "0006_remove_customuser_company_id_customuser_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="CustomUser",
                to="company.company",
            ),
        ),
    ]
