# Generated by Django 5.1.1 on 2024-09-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_options"),
        ("users", "0006_invitation"),
    ]

    operations = []
