# Generated by Django 5.1.1 on 2024-09-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customuser_email"),
        ("users", "0007_merge_0006_alter_customuser_options_0006_invitation"),
    ]

    operations = []
