# Generated by Django 5.1.1 on 2024-09-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customuser_email"),
        ("users", "0009_notification_user"),
    ]

    operations = []
