# Generated by Django 5.1 on 2024-09-03 07:39

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=255)),
                ("supplier", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("safety_stock", models.IntegerField(null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("note", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("out_stock", "缺貨"),
                            ("low_stock", "低於安全庫存量"),
                            ("normal", "正常"),
                        ],
                        default="normal",
                        max_length=50,
                        protected=True,
                    ),
                ),
            ],
        ),
    ]
