# Generated by Django 5.1 on 2024-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
