# Generated by Django 5.1.1 on 2024-09-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="safety_stock",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
