# Generated by Django 5.1 on 2024-08-29 16:36

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("out_stock", "缺貨"),
                    ("low_stock", "低於安全庫存量"),
                    ("normal", "正常"),
                ],
                default="normal",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
