# Generated by Django 5.1.1 on 2024-09-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventory_state"),
        ("inventory", "0002_remove_inventory_delete_at_inventory_deleted_at"),
    ]

    operations = []
