# Generated by Django 5.1.1 on 2024-09-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_company'),
        ('inventory', '0003_merge_20240921_1837'),
    ]

    operations = [
    ]
