# Generated by Django 5.1.1 on 2024-09-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_inventory_number"),
        ("inventory", "0004_merge_0003_inventory_company_0003_merge_20240921_1837"),
    ]

    operations = []
