# Generated by Django 5.1.1 on 2024-09-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="user",
            field=models.CharField(max_length=20),
        ),
    ]
