# Generated by Django 5.1.1 on 2024-09-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_remove_company_user_company_contact_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="contact_person",
            field=models.CharField(max_length=20),
        ),
    ]
