# Generated by Django 5.1.1 on 2024-09-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_company_contact_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="gui_number",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
