# Generated by Django 5.1.1 on 2024-09-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_company_gui_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="company_id",
        ),
    ]
