# Generated by Django 5.1.1 on 2024-09-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_remove_company_company_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="company_name",
            new_name="name",
        ),
    ]
