# Generated by Django 5.1.1 on 2024-09-23 08:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_rename_company_name_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="identifier",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
