# Generated by Django 5.1.1 on 2024-09-23 11:48

from django.db import migrations

def create_initial_companies(apps, schema_editor):
    Company = apps.get_model('company', 'Company')
    if not Company.objects.filter(id="1").exists():
        Company.objects.create(id="1",name='訪問公司', gui_number='12345678', address='地址A', contact_person='聯絡人A')

class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_company_identifier"),
    ]

    operations = [
        migrations.RunPython(create_initial_companies),
    ]
