# Generated by Django 5.1.1 on 2024-09-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
