# Generated by Django 5.1 on 2024-09-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
