# Generated by Django 5.1.1 on 2024-09-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchase_orders",
            "0002_purchaseorder_deleted_at_purchaseorder_state_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorder",
            old_name="total_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="purchaseorder",
            old_name="notes",
            new_name="note",
        ),
    ]
