# Generated by Django 5.1.1 on 2024-09-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0002_purchaseorder_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier_email",
            field=models.EmailField(max_length=254),
        ),
    ]
