# Generated by Django 5.1.1 on 2024-09-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchase_orders",
            "0002_purchaseorder_deleted_at_purchaseorder_state_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
