# Generated by Django 5.1 on 2024-09-06 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0002_alter_purchaseorder_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="order_date",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
