# Generated by Django 5.1.1 on 2024-09-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_purchaseorder_state_productitem'),
        ('purchase_orders', '0003_alter_purchaseorder_supplier_email'),
    ]

    operations = [
    ]
