# Generated by Django 5.1.1 on 2024-09-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0003_alter_purchaseorder_state"),
        ("purchase_orders", "0003_rename_total_amount_purchaseorder_amount_and_more"),
    ]

    operations = []
