# Generated by Django 5.1.1 on 2024-09-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0003_remove_purchaseorder_order_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="total_amount",
            field=models.PositiveIntegerField(),
        ),
    ]
