# Generated by Django 5.1.1 on 2024-09-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_rename_total_amount_purchaseorder_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='username',
            field=models.CharField(default='admin', max_length=150),
        ),
    ]
