# Generated by Django 5.1.1 on 2024-09-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_orders", "0003_alter_purchaseorder_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
