# Generated by Django 5.1.1 on 2024-09-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0004_rename_price_productitem_cost_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productitem",
            name="sale_price",
        ),
    ]
