# Generated by Django 5.1.1 on 2024-09-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0004_merge_20240918_0101"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="username",
            field=models.CharField(default="admin", max_length=150),
        ),
    ]
