# Generated by Django 5.1.1 on 2024-09-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0004_alter_purchaseorder_order_number"),
        ("purchase_orders", "0004_purchaseorder_company"),
    ]

    operations = []
