# Generated by Django 5.1.1 on 2024-09-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0005_purchaseorder_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_order_items",
                to="purchase_orders.purchaseorder",
            ),
        ),
    ]
