# Generated by Django 5.1.1 on 2024-09-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0005_purchaseorder_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(max_length=10),
        ),
    ]
