# Generated by Django 5.1.1 on 2024-09-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0005_merge_20240924_0009"),
        ("purchase_orders", "0006_alter_purchaseorder_order_number"),
    ]

    operations = []
