# Generated by Django 5.1.1 on 2024-09-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0006_alter_purchaseorder_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(max_length=11),
        ),
    ]
