# Generated by Django 5.1.1 on 2024-09-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0007_merge_20240925_1546"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(max_length=20),
        ),
    ]
