# Generated by Django 5.1.1 on 2024-09-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0007_alter_productitem_purchase_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
