# Generated by Django 5.1.1 on 2024-09-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0004_purchaseorder_is_finished"),
        ("purchase_orders", "0008_purchaseorder_updated_at"),
    ]

    operations = []
