# Generated by Django 5.1.1 on 2024-10-05 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_orders", "0010_productitem_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productitem",
            name="user",
        ),
    ]
