# Generated by Django 5.1 on 2024-08-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="create_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="delete_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="client",
            name="note",
            field=models.TextField(max_length=150, null=True),
        ),
    ]
