# Generated by Django 5.1.1 on 2024-09-08 01:51

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="state",
            field=django_fsm.FSMField(
                choices=[("often", "經常"), ("haply", "偶爾"), ("never", "從不")],
                default="never",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
