# Generated by Django 5.1.1 on 2024-09-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_remove_client_delete_at_client_deleted_at"),
        ("company", "0006_remove_company_company_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="company.company",
            ),
        ),
    ]
