# Generated by Django 5.1.1 on 2024-09-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_client_company"),
        ("clients", "0004_remove_client_delete_at_client_deleted_at"),
    ]

    operations = []
