# Generated by Django 5.1.1 on 2024-09-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_client_updated_at_alter_client_deleted_at"),
    ]

    operations = []
