# Generated by Django 5.1.1 on 2024-09-23 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_merge_20240924_0009'),
        ('company', '0009_auto_20240923_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='company.company'),
        ),
    ]
