# Generated by Django 5.1.1 on 2024-09-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_alter_client_email"),
        ("clients", "0009_client_user"),
    ]

    operations = []
