# Generated by Django 5.1.1 on 2024-09-21 15:50

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0003_alter_client_state"),
        ("inventory", "0002_alter_inventory_state"),
        ("products", "0002_alter_product_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=11, unique=True)),
                ("client_tel", models.CharField(max_length=15)),
                ("client_address", models.CharField(max_length=150)),
                ("client_email", models.EmailField(max_length=254)),
                ("amount", models.PositiveIntegerField()),
                ("username", models.CharField(default="admin", max_length=150)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[("貨運", "貨運"), ("自取", "自取")], max_length=20
                    ),
                ),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("pending", "待處理"),
                            ("progress", "進行中"),
                            ("finished", "已完成"),
                        ],
                        default="progress",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="clients.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrderProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered_quantity", models.PositiveIntegerField()),
                ("shipped_quantity", models.PositiveIntegerField()),
                ("sale_price", models.PositiveIntegerField()),
                ("subtotal", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales_orders.salesorder",
                    ),
                ),
                (
                    "stock_quantity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="inventory.inventory",
                    ),
                ),
            ],
        ),
    ]
