# Generated by Django 5.1.1 on 2024-09-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="order_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
