# Generated by Django 5.1 on 2024-09-02 12:22

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("sales_orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesorder",
            old_name="updated_at",
            new_name="last_updated",
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="state",
            field=django_fsm.FSMField(
                choices=[("unfinish", "未完成"), ("finish", "完成")],
                default="finish",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.RemoveField(
            model_name="salesorder",
            name="stock",
        ),
        migrations.AddField(
            model_name="salesorder",
            name="stock",
            field=models.ManyToManyField(to="inventory.inventory"),
        ),
    ]
