# Generated by Django 5.1.1 on 2024-09-21 08:59

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales_orders", "0002_salesorder_deleted_at_alter_salesorder_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "待處理"),
                    ("progress", "進行中"),
                    ("finished", "已完成"),
                ],
                default="progress",
                max_length=50,
                protected=True,
            ),
        ),
    ]
