# Generated by Django 5.1.1 on 2024-09-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_orders", "0003_alter_salesorder_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
