# Generated by Django 5.1.1 on 2024-09-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_orders", "0003_salesorder_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
