# Generated by Django 5.1.1 on 2024-09-21 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_state"),
        ("sales_orders", "0003_alter_salesorder_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesorder",
            old_name="price",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="salesorder",
            old_name="last_updated",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="salesorder",
            name="product",
        ),
        migrations.RemoveField(
            model_name="salesorder",
            name="quantity",
        ),
        migrations.AddField(
            model_name="salesorder",
            name="client_address",
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesorder",
            name="client_email",
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesorder",
            name="client_tel",
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesorder",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="order_number",
            field=models.CharField(default=0, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_method",
            field=models.CharField(
                choices=[("貨運", "貨運"), ("自取", "自取")], default=0, max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesorder",
            name="username",
            field=models.CharField(default="admin", max_length=150),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SalesOrderProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipped_quantity", models.PositiveIntegerField()),
                ("sale_price", models.PositiveIntegerField()),
                ("subtotal", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales_orders.salesorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
