# Generated by Django 5.1.1 on 2024-09-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_orders", "0004_salesorder_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
