# Generated by Django 5.1.1 on 2024-09-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_orders", "0004_rename_price_salesorder_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderproductitem",
            name="ordered_quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
