# Generated by Django 5.1.1 on 2024-09-20 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales_orders", "0005_salesorder_is_deleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesorder",
            old_name="is_deleted",
            new_name="is_finished",
        ),
    ]
