# Generated by Django 5.1.1 on 2024-09-21 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("sales_orders", "0005_salesorderproductitem_ordered_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_orders",
                to="inventory.inventory",
            ),
        ),
    ]
