# Generated by Django 5.1.1 on 2024-09-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales_orders", "0006_alter_salesorder_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesorderproductitem",
            old_name="order",
            new_name="sales_order",
        ),
    ]
